# Problema

Uma consideração importante no estudo de transferência de calor é a de determinar a distribuição de
temperatura assintótica de uma placa fina quando a temperatura em seu bordo é conhecida. Suponha que a placa na
Figura 2 represente uma seção transversal de uma barra de metal, com fluxo de calor desprezível na direção
perpendicular à placa. Sejam $T_1, T_2, \dots, T_6$ as temperaturas em seis vértices interiores do reticulado da Figura 1. A temperatura num vértice é aproximadamente igual à média dos quatro vértices vizinhos mais próximos - à esquerda, acima, à direita e abaixo. Por exemplo,

$$ T_1 = \frac{(10+20+T_2+T_4)}{4} \hspace{0.5cm} \text{ou} \hspace{0.5cm} 4T_1-T_2-T_4=30  $$

| <img src="figura2.png" width="300px"></img> |
|:--:|
|*Figura 1. Temperatura em seis vértices interiores do reticulado*|

**a)** Escreva um sistema de seis equações cuja solução forneça estimativas para as temperaturas $T_1, T_2, \dots, T_6$

**b)** Resolva o sistema linear obtido em **a)** utilizando o método de fatoração LU, sem e com pivotamento.

# Solução

## a) Equações

$$
T_1 = \frac{1}{4}(10 + 20 + T_2 + T_4) \\
T_2 = \frac{1}{4}(T_1 + 20 + T_3 + T_5) \\
T_3 = \frac{1}{4}(T_2 + 20 + 40 + T_6) \\
T_4 = \frac{1}{4}(10 + T_1 + T_5 + 20) \\
T_5 = \frac{1}{4}(T_4 + T_2 + T_6 + 20) \\
T_6 = \frac{1}{4}(T_5 + T_3 + 40 + 20)
$$

Logo,

$$ \begin{cases}
    4T_1 &-&  T_2 &+& 0T_3 &-&  T_4 &+& 0T_5 &+& 0T_6 &=& 30 \\
    -T_1 &+& 4T_2 &-& T_3  &+& 0T_4 &-& T_5  &+& 0T_6 &=& 20 \\
    0T_1 &-&  T_2 &+& 4T_3 &+& 0T_4 &+& 0T_5 &-&  T_6 &=& 60  \\
    -T_1 &+& 0T_2 &+& 0T_3 &+& 4T_4 &-& T_5  &+& 0T_6 &=& 30 \\
    0T_1 &-&  T_2 &+& 0T_3 &-&  T_4 &+& 4T_5 &-&  T_6 &=& 20 \\
    0T_1 &+& 0T_2 &-& T_3  &+& 0T_4 &-& T_5  &+& 4T_6 &=& 60
\end{cases} $$

Que resulta na matriz de coeficientes:

$$
\begin{bmatrix}
    4 & -1 & 0 & -1 & 0 & 0 \\
    -1 & 4 & -1 & 0 & -1 & 0 \\
    0 & -1 & 4 & 0 & 0 & -1 \\
    -1 & 0 & 0 & 4 & -1 & 0 \\
    0 & -1 & 0 & -1 & 4 & -1 \\
    0 & 0 & -1 & 0 & -1 & 4
\end{bmatrix}
$$


## b) [Fatoração LU](https://pt.wikipedia.org/wiki/Decomposi%C3%A7%C3%A3o_LU)

A fatoração de uma matriz $A$ é uma equação que expressa $A$ como o produto de duas ou mais matrizes. 

Na linguagem da ciência da computação, a expressão que representa $A$ na forma de um produto pode ser entendida como um processamento de dados, pois os dados são organizados em duas ou mais partes cujas estruturas, de alguma forma, são mais fáceis de lidar computacionalmente.

A fatoração LU é amplamente aplicada quando quer-se resolver uma sequência de equações, todas com a mesma matriz de coeficientes, por exemplo:

$$ Ax=b_1, \quad Ax=b_2, \quad \cdots, Ax=b_n. $$

Seu resultado é a descrição de $A$ como o produto de duas matrizes, $L$ e $U$, matrizes triangulares inferior e superior, respectivamente.

$$ A = LU $$

$$ 
\begin{bmatrix}
a_{11} & a_{12} & a_{13} & \dots & a_{1n} \\
a_{21} & a_{22} & a_{23} & \dots & a_{2n} \\
a_{21} & a_{32} & a_{33} & \dots & a_{3n} \\
\dots \\
a_{m1} & a_{m2} & a_{m3} & \dots & a_{mn} \\
\end{bmatrix}

= 

\begin{bmatrix}
l_{11} & 0 & 0 & \dots & 0 \\
l_{21} & l_{22} & 0 & \dots & 0  \\
l_{31} & l_{32} & l_{33} & \dots & 0  \\
\dots \\
l_{m1} & l_{m2} & l_{m3} & \dots & l_{mn} \\
\end{bmatrix}

\begin{bmatrix}
u_{11} & u_{12} & u_{13} & \dots & u_{1n} \\
0 & u_{22} & u_{23} & \dots & u_{2n} \\
0 & 0 & u_{33} & \dots & u_{3n} \\
\dots \\
0 & 0 & 0 & \dots & u_{mn} \\
\end{bmatrix}

$$

In [4]:
import numpy as np
from IPython.display import display, Markdown, Latex
from furg_imef_verificador_respostas import Verificador

def verificar_resposta(x):
    verificador = Verificador()
    verificador.verificar_resposta(x)


In [5]:
A = np.array([
    [ 4, -1,  0, -1,  0,  0],
    [-1,  4, -1,  0, -1,  0],
    [ 0, -1,  4,  0,  0, -1],
    [-1,  0,  0,  4, -1,  0],
    [ 0, -1,  0, -1,  4, -1],
    [ 0,  0, -1,  0, -1,  4]
])

b = np.array([30, 20, 60, 30, 20, 60])

### Sem pivotamento

In [17]:
#A2 = A.copy()
#A_0 = A2.copy()
As = [A.copy()]
Ls = [np.eye(A.shape[0])]

for j in range(As[0].shape[0]):
    A_i = As[j]
    display(A_i[j, :])
    a_nn = A_i[j,j]
    
    A_j = A_i.copy()
    #L_n = Ls[j].copy()
    L_n = np.eye(A_i.shape[0])
    for i in range(j+1, A_i.shape[1]):
        a_in = A_j[i,j]
        l_in = -a_in/a_nn
        #display(A_i[i,:]*l_in+A_j[i,:])
        #A_j[i,:] = (A_i[j,:]*l_in+A_j[i,:])
        L_n[i, j] = l_in
        
    A_n = L_n@A_j
    
    As.append(A_n)
    Ls.append(L_n)

#display(Ls)
display(A)
L = np.eye(A.shape[0])
for L_i in Ls:
    L = L@np.linalg.inv(L_i)
display(L.round(1))
display((L*As[-1]).round(1))
#display((Ls[-1]@As[-1]).round())
    

array([ 4, -1,  0, -1,  0,  0])

array([ 0.  ,  3.75, -1.  , -0.25, -1.  ,  0.  ])

array([ 0.        ,  0.        ,  3.73333333, -0.06666667, -0.26666667,
       -1.        ])

array([ 0.        ,  0.        ,  0.        ,  3.73214286, -1.07142857,
       -0.01785714])

array([ 0.        ,  0.        ,  0.        ,  0.        ,  3.40669856,
       -1.07655502])

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       3.39185393])

array([[ 4, -1,  0, -1,  0,  0],
       [-1,  4, -1,  0, -1,  0],
       [ 0, -1,  4,  0,  0, -1],
       [-1,  0,  0,  4, -1,  0],
       [ 0, -1,  0, -1,  4, -1],
       [ 0,  0, -1,  0, -1,  4]])

array([[ 1. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [-0.2,  1. ,  0. ,  0. ,  0. ,  0. ],
       [ 0. , -0.3,  1. ,  0. ,  0. ,  0. ],
       [-0.2, -0.1, -0. ,  1. ,  0. ,  0. ],
       [ 0. , -0.3, -0.1, -0.3,  1. ,  0. ],
       [ 0. ,  0. , -0.3, -0. , -0.3,  1. ]])

array([[ 4. , -0. ,  0. , -0. ,  0. ,  0. ],
       [-0. ,  3.8, -0. , -0. , -0. ,  0. ],
       [ 0. , -0. ,  3.7, -0. , -0. , -0. ],
       [-0. , -0. , -0. ,  3.7, -0. , -0. ],
       [ 0. , -0. , -0. , -0. ,  3.4, -0. ],
       [ 0. ,  0. , -0. , -0. , -0. ,  3.4]])

### Com pivotamento

# Decomposição QR

In [18]:
import math 

def proj(u, v):
    return np.dot(u, v) / np.dot(u, u) * u

def QR_decomp(A):
    u = []
    for i in range(A.shape[1]):
        u.append(
            A[:,i] - np.sum([ proj(u[j], A[:, i]) for j in range(i) ], axis=0 )
        )

    Q = np.array([u[i]/math.sqrt(np.dot(u[i],u[i])) for i in range(len(u))]).T

    R = []
    for i in range(A.shape[0]):
        R.append(
            [ np.dot(Q[:,i], A[:,j])*(1-max(0, min(i-j,1))) for j in range(A.shape[1]) ]
        )
    R = np.array(R)

    return Q, R

# Resolve um sistema de equações cuja matriz de coeficientes é 
# do tipo triangular superiora.
def resolver_U(U, b):
    x = np.zeros(U.shape[1])
    for i in reversed(range(U.shape[0])):
        x[i]= ( b[i] - np.sum([U[i,j]*x[j] for j in range(i+1, U.shape[0])]) ) / U[i,i]
    return x


Q, R = QR_decomp(A)
display(R.round(2), (Q.T@b).round(2))
x = resolver_U(R, Q.T@b)

verificador.verificar_resposta(x)


array([[ 4.24, -1.89,  0.24, -1.89,  0.47,  0.  ],
       [-0.  ,  3.93, -1.92, -0.4 , -1.81,  0.51],
       [-0.  , -0.  ,  3.77, -0.08, -0.42, -1.86],
       [ 0.  , -0.  ,  0.  ,  3.78, -2.08,  0.28],
       [ 0.  ,  0.  ,  0.  , -0.  ,  3.32, -2.2 ],
       [ 0.  , -0.  ,  0.  , -0.  ,  0.  ,  3.06]])

array([16.5 ,  0.28, 41.5 , 27.71, 11.42, 83.11])

Resposta correta!


True